version: '3.9'

services:
  app:
    build: .
    container_name: setup-nodejs
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3008:3008' 
  db: 
    container_name: postgres-container
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/data/postgres  
volumes:
  pgdata:  
    driver: local