version: '3.9'

services:
  app:
    container_name: setup-nodejs
    command: sh -c "npx prisma migrate dev Company && yarn start"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3000
    ports:
      - 3000:3000 
  database: 
    image: postgres
    container_name: postgres-container
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres  
volumes:
  pgdata:  
    driver: local